### ISSUE TITLE
【@殷智伟】天气预报的接口

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#1]
- 天气预报API
- 开关某个设备（主页设备开关功能）
- 设备信息获取（设备信息是如何获取的）
- 执行某个场景API 缺少
- 登录之后的API 不带token也可以，是不是就没有登录过期这种说法了

**Comment by yinzw** [comment]
1，天气预报功能，前台能提供当前地址嘛，拿到地址后后台可以获取天气

**Comment by yinzw** [comment]
2，开关设备都是通过mqtt送信来做的，需要看下原来的前台代码

**Comment by weiki08** [comment]
> 天气预报API
> 天气预报功能，前台能提供当前地址嘛，拿到地址后后台可以获取天气

可以的。后台把这API设计出来吧！前台把地址传过去

**Comment by yinzw** [comment]
>可以的。后台把这API设计出来吧！前台把地址传过去

我查了下，如果能拿到坐标的话就没必要再调后台了，按照下面的顺序来做就行了。
通过下面的百度api可以取到天气：
http://api.map.baidu.com/telematics/v3/weather?location=116.305145,39.982368&output=json&ak=yourkey

参照下面的页面吧。ak的话群里说过，应该有。
https://www.cnblogs.com/txw1958/p/baidu-weather-forecast-api.html

**Comment by yinzw** [comment]
>登录之后的API 不带token也可以，是不是就没有登录过期这种说法了

现在既存的代码里面把对token的check给注释掉了，现在应该没有过期这种说法。

    checkToken: function(req, res, next) {
        // Pass token check if in user api
        if (req.path.indexOf('user') != -1) {
            console.log('PASSED TOKEN CHECK: USER', req.path.indexOf('user'));
            return next();
        }

        // // Pass token check if local test
        // var ignoreIPs = ['::1', '::ffff:127.0.0.1'];
        // if (ignoreIPs.indexOf(req.connection.remoteAddress) != -1) {
        //     // do not track the log of local
        //     console.log('PASSED TOKEN CHECK: LOCAL', req.connection.remoteAddress);
        //     return next();
        // }

        var tokenSi = {
            userId: req.body.userId,
        };

        var userModel = tutu.models.user;
        userModel.one(tokenSi, function(err, user) {
            if (err) return next(err);

            if (!user) {
                tutu.logger.info('FAILED TOKEN CHECK: user not exist', 'userid:', req.body.userId);
                return res.send({ errCode: '903', errMsg: 'userId不存在' });
            }

            // if (user && user.token == req.body.token) {
            //     next();
            // } else {
            //     tutu.logger.info('FAILED TOKEN CHECK', 'userid:', user.userId, 'phone:', user.phone, 'send:', req.body.token, 'server:', user.token);
            //     return res.send({ errCode: '902', errMsg: 'TOKEN有误', send: req.body.token, server: user.token });
            // }
            next();
        });
    },

**Comment by weiki08** [comment]
目前百度APP端没有接口，这个看怎么办？

**Comment by weiki08** [comment]
高德的天气预报
