### ISSUE TITLE
【@IOS】POST /share/invit 邀请分享

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#10]
这个API的参数是shareUserId

画面设计参数是

- 用户名
- 手机号
- userId

这个API需要改一下

**Comment by yinzw** [comment]
看了下现在的DB, user表里面存在40条用户名为空， 手机号='nophone'的数据， 通过这两个参数查找shareUserId会不会有问题， 前台有check嘛

**Comment by yinzw** [comment]
API: /v1/share/invite_v2
再确认一点：
参数用户名和手机号对应的用户DB中一定存在嘛，如果不存在的话将无法取到shareUserId, 后台会返回107，手机号未注册错误。
