### ISSUE TITLE
【画面】用户帐号画面

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#12]
![2-6-1](https://user-images.githubusercontent.com/14228737/44308373-80e80280-a3ef-11e8-8361-f5d5a88459d4.png)

这个画面的第一条数据是这个帐号本人吗？而且还有编辑功能

自己的信息不是有个人信息修改之类的画面吗？这里设计是不是重复的

**Comment by sangliujian** [comment]
这个编辑取消了，现在是这个样子
![dtsi5644dv2ch v7n i fg](https://user-images.githubusercontent.com/15883084/44572395-45b24e80-a7b6-11e8-8cd8-85d29dff8efc.png)
前面少了一个名字，是因为名字为null,只是后面的编辑现在删除了

**Comment by weiki08** [comment]
【美工回答】画面的第一条数据是本人账号，编辑功能删除取消掉。 账号本人是可以有权限删除所有共享人的数据，有权限编辑共享人的信息。 共享人无权限编辑，就不出现编辑的样式。
