### ISSUE TITLE
【API】场景删除API

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#13]
好像没有这个API

**Comment by yinzw** [comment]
已经添加：
URL:
/scene/delete  POST方式

参数：
用户Id：userId
场景Id：sceneId

**Comment by weiki08** [comment]
如果是删除地理围栏的场景的时候，要把百度上的地理围栏同时删除

http://lbsyun.baidu.com/index.php?title=ios-yingyan/guide/geo-fencing

**Comment by weiki08** [comment]
已经追加
