### ISSUE TITLE
【@殷智伟】微信登录

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#17]
微信登录的时候，怎么把微信的Token和用户绑定起来的，

POST /user/editProfile 也没有wechatToken 这个参数

**Comment by yinzw** [comment]
DB中存在wechatToken这个字段， 可以在接口/user/editProfile中把这个字段加进去。
登录的接口需要改吗，还是只要改editProfile

**Comment by weiki08** [comment]
登录接口也要改的吧，因为有微信登录这个选项

**Comment by yinzw** [comment]
/user/editProfile中已经添加wechatToken端口。另外， 登录接口不需要修改，既存有接口
/v1/user/thirdPartyLogin是专门用来做微信端绑定登录的，参数是
req.body.type == 'wechat' 和 req.body.data.wechatToken。
但是需要注意的是，这边的关联微信是下面这个，请确认一下是否正确
wechatAppId: "wxff×××××××××e6cb",
wechatAppSecret: "7322×××××××××××××××××e453a",
如果需要修改，我这边改一下

**Comment by weiki08** [comment]
传入的参数为
type
wechatToken（这里的值为第一步返回的code）
参考链接 
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317851&token=&lang=zh_CN
