### ISSUE TITLE
【@殷智伟】房间里面所能追加设备有没有上限

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#19]
一个topic 下的msg L1_L2_C1_C2_C3_C4 ，topic是以房间为单位的，那这个房间所能添加的设备是不是就是调光 最多两个（L1 L2）窗帘最多4个的意思吗？

msg格式
> DA|XI_R1_R2_R3_R4_RS_L1_L2_C1_C2_C3_C4_SC_AC|

**Comment by yinzw** [comment]
是的， 最多只能是两个可调灯， 4个窗帘，如果前端没有限制，那需要再确认
