### ISSUE TITLE
【@殷】追加的API-未绑定房间的设备一览API/设备绑定房间API/设备解绑房间API

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#21]
昨天和张悦讨论了下式样，需要追加下面的API

- 未绑定房间的设备一览API
- 设备绑定房间API
- 设备解绑房间API

**Comment by yinzw** [comment]
未绑定房间的设备一览API:
/v1/device/listWithUnbind post形式，参数：userId

**Comment by yinzw** [comment]
设备绑定房间API
设备解绑房间API
URL：/v1/device/updateDeviceRoomId
必须参数：
userId
id
可选参数：
roomId (为空时解除绑定）
