### ISSUE TITLE
【BUG】定时任务开启时，默认是关闭状态

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#26]
![image](https://user-images.githubusercontent.com/14228737/48655259-b1235980-ea4f-11e8-9196-7cd4ab4ba9b2.png)

**Comment by weiki08** [comment]
这个默认是关闭的

**Comment by sangliujian** [comment]
这个默认是开启的~
还有，创建好的情景数据中，setting字段里
缺少定时任务的ID
![image](https://user-images.githubusercontent.com/15883084/48815930-2f973880-ed7b-11e8-8846-3be6fa6a8644.png)
这是创建的任务的数据
![image](https://user-images.githubusercontent.com/15883084/48815989-6cfbc600-ed7b-11e8-9b4c-01e77da61f58.png)
不知道是什么意思

**Comment by weiki08** [comment]
已经修改
