### ISSUE TITLE
【BUG】多路继电器问题

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#31]
在创建情景的时候，是把多路继电器放入列表中，
但是这样操作过后，会把原来为了方便配置情景把多路设备拆分成的多路单独设备又重新整合成一个设备。

![image](https://user-images.githubusercontent.com/14228737/48655332-6a822f00-ea50-11e8-8dae-c39f8d6fde47.png)

 这样就导致了修改情景没法正常确认具体设备，所以加入deviceid和devicename参数，为了在创建情景时候把继电器设备存放为一条数据后还能有办法拆分成单独的设备

**Comment by weiki08** [comment]
![image](https://user-images.githubusercontent.com/14228737/48661792-c8dff980-eab2-11e8-9798-8d46619dd810.png)

**Comment by sangliujian** [comment]
额，这里我没有说清楚。。怪我，格式是按照你定的来
{
    "type":"byLocation",//模式 byHand,byAuto
    "time":"18:30", //定时时间
    "week":[ //星期
        1,
        2,
        3,
        4,
        5,
        6,
        7
    ],
    "latitude":32.041544, 
    "longitude":118.767413,
    "distance":55, //地址围栏的距离
    "status":"0", //当前scene的开关状态
    "isLeave":"0"//1：离开某地，2：到达某地，
    "entityName":"entity"//entity实体 字母数字下划线
    "scheduleId":1,
    “fenceID”：1,
    "devices":[
        {
            "id":0,
            "deviceId":"",//设备ID
            "wifiMac":"",
            "mac":"",
            "deviceName":"",//设备名称
            "deviceType":208,//设备类型-空调
            "deviceSetting":{
                "isOn":1,//0:关，1:开
                "model":0,// 0，1，2，3 对应画面的那4个状态
                "temperature":37,//温度
                "speed":1,//风速 0，1，2，3 对应画面的那4个风速
                "brightness":""
            }
        },
        {
            "id":0,
            "wifiMac":"",
            "mac":"",
            "deviceId":"",
            "deviceName":"",
            "deviceType":211,//设备类型-灯灯光调光型
            "deviceSetting":{
                readyState:[
                        {"id":1, "status":"0","level":0,"deviceId":”1740“,"deviceName":“灯光调光1”}, 
                        {"id":2, "status":"1","level":99."deviceId":”1741“,"deviceName":“灯光调光2”}
                ]
            }
        },
        {
            "id":0,
            "wifiMac":"",
            "mac":"",
            "deviceId":"",
            "deviceName":"",
            "deviceType":210,//设备类型-灯灯光开关型
            "deviceSetting":{
                readyState:[
                        {"id":1, "status":"0","deviceId":”1740“,"deviceName":“灯光开关1”}, 
                        {"id":2, "status":"1","deviceId":”1741“,"deviceName":“灯光开关2”}
                ]
            }
        },
        {
            "id":0,
            "deviceId":"",
            "wifiMac":"",
            "mac":"",
            "deviceName":"",
            "deviceType":212,//设备类型-窗帘
            "deviceSetting":{
                readyState:[
                        {"id":1, "status":"0","deviceId":”1740“,"deviceName":“窗帘1”}, 
                        {"id":2, "status":"1"."deviceId":”1741“,"deviceName":“窗帘2”}
                ]
            }
        },
        {
            "id":0,
            "deviceId":"",
            "wifiMac":"",
            "mac":"",
            "deviceName":"",
            "deviceType":209,//设备类型-地暖
            "deviceSetting":{
                "isOn":1,
                "model":"",
                "temperature":37,
                "speed":"",
                "brightness":""
            }
        }
    ]
}


你的参数中
![image](https://user-images.githubusercontent.com/15883084/48817479-a0415380-ed81-11e8-968a-77948ecee515.png)

我截取了一段，为什么会有这两个参数，你写的格式中没有呀

**Comment by weiki08** [comment]
有的，这两个参数需要的

**Comment by weiki08** [comment]
已经修改
