### ISSUE TITLE
【画面】POST /device/create 设备追加API

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#4]
这个API
参数

- MAC
- powerRate

不是知道来源是什么？ 画面没有这些入力

缺少

- 设备品牌

**Comment by yinzw** [comment]
>这个API参数
>MAC
>powerRate
>不是知道来源是什么？ 画面没有这些入力

我查了下，前台画面应该是通过下面3步添加设备：
 * 1. 检查WIFI是否连接，
 * 2. 连接成功之后， 检测设备
 * 3. 列出所有的设备， 用户选择添加

在检测设备是应该可以拿到powerRate，代码可能不在我上次给你的代码里面，比较大，私信给你。

>设备品牌
应该是api里面漏了，字段brand, DB里面有，直接传过来就可以了。

**Comment by weiki08** [comment]
功率为必须

**Comment by weiki08** [comment]
这个画面的设备应该是选出来的吧

**Comment by weiki08** [comment]
结论：smartlink扫描
