### ISSUE TITLE
【API】/scene/list

### ISSUE THREAD

**Issue by weiki08** [BolangIssues/Bolang#7]
- 场景列表

这个API的返回值中，看不出是 【手动】【定时】【地理围栏】类型

请返回一个字段作为区分

**Comment by yinzw** [comment]
【手动】【定时】【地理围栏】只是一个固定区分嘛，从哪边取？有具体式样嘛
我查了下DB，字段status里面有很多信息，是否就是你要的数据：
+----+--------+--------------------------------------+------+--------+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id | name   | userId                               | sort | status | createDate          | settings                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+----+--------+--------------------------------------+------+--------+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  1 | 回家   | 9fe4aea3-950a-4d94-826c-696b6bbc5942 | NULL | NULL   | 2017-04-26 07:43:13 | {"tasks":{"94":{"MAC":"F0FE6B2F980E0000","typeModel":{"id":"208","name":"空调"}}},"conditions":[{"type":"locate","value":"距离江苏省无锡市梁溪区南湖大道XXXXX500米","extra":{"latitude":31.52271294487847,"longitude":120.3164634874132,"address":"江苏省无锡市梁溪区南湖大道靠近XXXXX,"radius":"500"}}]}                                                                                                                                              |
|  2 | 离家   | 9fe4aea3-950a-4d94-826c-696b6bbc5942 | NULL | NULL   | 2017-04-26 07:43:13 | {"tasks":{"38":{"MAC":"F0FE6B2F980E0000","typeModel":{"id":"208","name":"空调"},"power":true},"94":{"MAC":"F0FE6B2F980E0000","typeModel":{"id":"208","name":"空调"}}},"conditions":[{"type":"locate","value":"距离江苏省无锡市梁溪区南湖XXXXX1000米","extra":{"latitude":31.52272488064236,"longitude":120.3164898003472,"address":"江苏省无锡市梁溪区南湖大道靠近XXXX","radius":"1000"}}]}                                                        |
|  8 | 离家   | e2f90b69-54d9-4c76-bd9e-171eaf53b7a6 | NULL | NULL   | 2017-05-06 12:27:14 | {"tasks":{"46":{"MAC":"F0FE6B2F97580000","typeModel":{"id":"208","name":"空调"},"power":true}},"conditions":[{"type":"alarm","value":"5分钟后","extra":300}]}                                                                                                                                                                                                                                                                                                                         |
|  9 | 回家   | e2f90b69-54d9-4c76-bd9e-171eaf53b7a6 | NULL | NULL   | 2017-05-06 12:27:14 | {"tasks":{"46":{"MAC":"F0FE6B2F97580000","typeModel":{"id":"208","name":"空调"},"power":false,"temp":35},"50":{"MAC":"0186B23A00158D00","typeModel":{"id":"217","name":"壁挂空调 "}}},"conditions":[]}

**Comment by weiki08** [comment]
这个status 不是那个手动还是自动的区分，我觉得我知道了，
是从设定里面提取的

```
"type":"locate",
"type":"alarm"
```

下面是那个文档上写的

> "status": "string,启用1，未启用0"

**Comment by weiki08** [comment]
后台代码

```
export const TRIGGER_TYPE = {
    TIME: 'alarm',
    LOC: 'locate'
}
```

**Comment by weiki08** [comment]
close
